# Disable sudo to speed up the build
sudo: false

language: python

# python versions to test
python:
  - "3.7"
  - "3.8"
  - "3.9"

# test with pytest
script:
  - pytest

# install dependencies
install:
  - pip install cbor2
  - pip install py-cid
  - pip install py-multihash
  - pip install codecov
  - pip install pytest pytest-cov

# run the unit test
script:
  - pytest --cov=./dag_cbor/

# push the results back to codecov
after_success:
  - codecov
